/*
 * Alarmservice Demo
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

// Tsify generates non-snake-case methods. We need to allow that here in order to keep clippy from escalating.
#![allow(non_snake_case)]

use crate::models;

//use serde::{Deserialize, Serialize};
use serde_derive::Serialize;
use serde_derive::Deserialize;

use tsify_next::Tsify;

#[derive(Tsify, Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
#[tsify(into_wasm_abi, from_wasm_abi)]
pub struct AlarmDto {
    #[serde(rename = "reason", skip_serializing_if = "Option::is_none")]
    
    pub reason: Option<String>,
    #[serde(rename = "acknowledged", skip_serializing_if = "Option::is_none")]
    
    pub acknowledged: Option<bool>,
    #[serde(rename = "timestamp", skip_serializing_if = "Option::is_none")]
    
    pub timestamp: Option<String>,
    #[serde(rename = "alarmId", skip_serializing_if = "Option::is_none")]
    
    pub alarm_id: Option<i64>,
    #[serde(rename = "roomId", skip_serializing_if = "Option::is_none")]
    
    pub room_id: Option<i64>,
}

impl AlarmDto {
    pub fn new() -> AlarmDto {
        AlarmDto {
            reason: None,
            acknowledged: None,
            timestamp: None,
            alarm_id: None,
            room_id: None,
        }
    }
}

