/*
 * Alarmservice Demo
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

#![allow(dead_code)]
#![allow(unused_imports)]
#![allow(clippy::to_string_trait_impl)]
#![allow(clippy::new_without_default)]

pub mod alarm_dto;
pub use self::alarm_dto::AlarmDto;
pub mod event_dto;
pub use self::event_dto::EventDto;
pub mod room_dto;
pub use self::room_dto::RoomDto;
pub mod schedule_dto;
pub use self::schedule_dto::ScheduleDto;
